# Generated by Django 3.0.8 on 2020-08-07 12:32

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('content', tinymce.models.HTMLField()),
                ('date', models.DateTimeField()),
                ('feature_image', models.ImageField(upload_to='events/')),
                ('slug', models.SlugField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='events_file/')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('content', tinymce.models.HTMLField()),
                ('date', models.DateTimeField()),
                ('feature_image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('file', models.FileField(blank=True, null=True, upload_to='news_file/')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Department')),
                ('program', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Program')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('content', tinymce.models.HTMLField()),
                ('date', models.DateTimeField()),
                ('feature_image', models.ImageField(upload_to='notice/')),
                ('file', models.FileField(blank=True, null=True, upload_to='notice_file/')),
                ('slug', models.SlugField(blank=True)),
                ('department', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Department')),
                ('program', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Program')),
            ],
        ),
        migrations.CreateModel(
            name='NoticeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='notice/')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Notice')),
            ],
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.News')),
            ],
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Event')),
            ],
        ),
    ]
