# Generated by Django 3.0.8 on 2020-08-07 12:32

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('header', models.CharField(max_length=254)),
                ('content', tinymce.models.HTMLField()),
                ('image', models.ImageField(upload_to='custom_pages/')),
                ('is_active', models.CharField(choices=[('T', 'Active'), ('F', 'In-Active')], max_length=1)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dean', models.CharField(max_length=100)),
                ('dean_image', models.ImageField(upload_to='department/dean/')),
                ('header', models.CharField(max_length=254)),
                ('content', tinymce.models.HTMLField()),
                ('feature_image', models.ImageField(upload_to='department/feature/')),
                ('is_active', models.CharField(choices=[('T', 'Active'), ('F', 'In-Active')], max_length=1)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dean', models.CharField(max_length=100)),
                ('dean_image', models.ImageField(upload_to='faculty/dean/')),
                ('header', models.CharField(max_length=254)),
                ('content', tinymce.models.HTMLField()),
                ('feature_image', models.ImageField(upload_to='faculty/')),
                ('is_active', models.CharField(choices=[('T', 'Active'), ('F', 'In-Active')], max_length=1)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dean', models.CharField(max_length=100)),
                ('dean_image', models.ImageField(upload_to='faculty/dean/')),
                ('header', models.CharField(max_length=254)),
                ('content', tinymce.models.HTMLField()),
                ('feature_image', models.ImageField(upload_to='faculty/')),
                ('is_active', models.CharField(choices=[('T', 'Active'), ('F', 'In-Active')], max_length=1)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dean', models.CharField(max_length=100)),
                ('dean_image', models.ImageField(upload_to='program/dean/')),
                ('header', models.CharField(max_length=254)),
                ('content', tinymce.models.HTMLField()),
                ('feature_image', models.ImageField(upload_to='program/feature/')),
                ('is_active', models.CharField(choices=[('T', 'Active'), ('F', 'In-Active')], max_length=1)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('flag', models.IntegerField()),
                ('department', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Department')),
                ('institute', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Institute')),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=254)),
                ('file', models.FileField(upload_to='syllabus/')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Department')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Program')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Faculty'),
        ),
        migrations.AddField(
            model_name='department',
            name='institute',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Institute'),
        ),
    ]
