# Generated by Django 3.0.8 on 2020-07-08 07:38

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('header', models.CharField(max_length=254)),
                ('content', tinymce.models.HTMLField()),
                ('image', models.ImageField(upload_to='custom_pages/')),
                ('is_active', models.CharField(choices=[('T', 'Active'), ('F', 'In-Active')], max_length=1)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dean', models.CharField(max_length=100)),
                ('dean_image', models.ImageField(upload_to='department/dean/')),
                ('header', models.CharField(max_length=254)),
                ('content', tinymce.models.HTMLField()),
                ('feature_image', models.ImageField(upload_to='department/feature/')),
                ('is_active', models.CharField(choices=[('T', 'Active'), ('F', 'In-Active')], max_length=1)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dean', models.CharField(max_length=100)),
                ('dean_image', models.ImageField(upload_to='program/dean/')),
                ('header', models.CharField(max_length=254)),
                ('content', tinymce.models.HTMLField()),
                ('feature_image', models.ImageField(upload_to='program/feature/')),
                ('is_active', models.CharField(choices=[('T', 'Active'), ('F', 'In-Active')], max_length=1)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
