# Generated by Django 3.0.8 on 2020-07-08 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(max_length=254)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Program')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/program/')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.ProgramImage')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(max_length=254)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Department')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/department/')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.DepartmentImage')),
            ],
        ),
    ]
