# Generated by Django 3.0.8 on 2020-08-07 12:27

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
                ('image1', models.ImageField(upload_to='aboutus/')),
                ('image2', models.ImageField(upload_to='aboutus/')),
                ('image3', models.ImageField(upload_to='aboutus/')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=14)),
                ('address', models.CharField(max_length=254)),
                ('contact_info', models.TextField()),
                ('logo_img', models.ImageField(upload_to='images/')),
                ('header_text', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=254)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='Message_From_Chief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_name', models.CharField(max_length=254)),
                ('message', models.TextField()),
                ('image', models.ImageField(upload_to='chiefs/')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=254)),
                ('content', models.TextField()),
                ('photo', models.ImageField(upload_to='slider/')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, max_length=254)),
                ('twitter', models.CharField(blank=True, max_length=254)),
                ('google_plus', models.CharField(blank=True, max_length=254)),
                ('linkedin', models.CharField(blank=True, max_length=254)),
                ('youtube', models.CharField(blank=True, max_length=254)),
            ],
        ),
    ]
